CREATE TABLE blacklisted_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    expiry_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_blacklisted_tokens PRIMARY KEY (id)
);

ALTER TABLE blacklisted_tokens
    ADD CONSTRAINT uc_blacklisted_tokens_token UNIQUE (token);