CREATE TABLE url_table
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_url VARCHAR(255)                            NOT NULL,
    short_url    VARCHAR(255),
    custom_alias VARCHAR(255),
    description  VARCHAR(255),
    user_id      BIGINT                                  NOT NULL,
    click_count  BIGINT                                  NOT NULL,
    is_active    BOOLEAN                                 NOT NULL,
    valid_since  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    valid_until  TIMESTAMP WITHOUT TIME ZONE,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_deleted   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_url_table PRIMARY KEY (id)
);

ALTER TABLE url_table
    ADD CONSTRAINT uc_url_table_short_url UNIQUE (short_url);

ALTER TABLE url_table
    ADD CONSTRAINT FK_URL_TABLE_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);