CREATE TABLE user_table
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username                       VARCHAR(255)                            NOT NULL,
    password                       VARCHAR(255)                            NOT NULL,
    email                          VARCHAR(255)                            NOT NULL,
    first_name                     VARCHAR(255)                            NOT NULL,
    last_name                      VARCHAR(255)                            NOT NULL,
    phone_number                   VARCHAR(255)                            NOT NULL,
    address                        VARCHAR(255),
    provider                       VARCHAR(255),
    is_active                      BOOLEAN                                 NOT NULL,
    last_login                     TIMESTAMP WITHOUT TIME ZONE,
    is_enabled                     BOOLEAN                                 NOT NULL,
    is_account_non_expired         BOOLEAN                                 NOT NULL,
    is_credentials_non_expired     BOOLEAN                                 NOT NULL,
    is_account_non_locked          BOOLEAN                                 NOT NULL,
    verification_token             VARCHAR(255),
    verification_code              VARCHAR(255),
    verification_token_expiry      TIMESTAMP WITHOUT TIME ZONE,
    max_verification_code_attempts INTEGER,
    reset_password_token           VARCHAR(255),
    reset_password_code            VARCHAR(255),
    reset_password_token_expiry    TIMESTAMP WITHOUT TIME ZONE,
    max_reset_password_attempts    INTEGER,
    created_at                     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_deleted                     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_user_table PRIMARY KEY (id)
);

ALTER TABLE user_table
    ADD CONSTRAINT uc_user_table_email UNIQUE (email);

ALTER TABLE user_table
    ADD CONSTRAINT uc_user_table_phone_number UNIQUE (phone_number);