spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://dev-db:5432/admin-api
    username: devuser
    password: devpass
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        show_sql: true

server:
  port: 8082
  servlet:
    context-path: /listener-api